version: 2.1        
orbs:
  codecov: codecov/codecov@3.2.4

executors:
  master:
    docker:
      - image: dawidblom/etna:latest
        auth:
          username: $DOCKERHUB_USERNAME 
          password: $DOCKERHUB_PASSWORD 

jobs:
  build:
    executor: master
    steps:
      - checkout
      - run:
          name: Building Project
          command: |
            ./Build.sh Release

  static_code_analysis:
    executor: master
    steps:
      - checkout
      - run:
          name: Static Code Analysis
          command: | 
            ./Build.sh StaticAnalysis

  unit_tests:
    executor: master
    steps:
      - checkout
      - codecov/upload
      - run:
          name: Unit Tests 
          command: | 
            ./Build.sh UnitTest

  code_coverage:
    executor: master
    steps:
      - checkout      
      - run:
          name: Code Coverage
          command: |
            ./Build.sh CodeCoverage
            ./CodeCoverage.sh


workflows:
  project_workflow:
    jobs:
      - build:
          context:
            - dockerhub_credentials

      - static_code_analysis:
          context:
            - dockerhub_credentials
          requires:
            - build

      - unit_tests:
          context:
            - dockerhub_credentials
            - cpputest_location
              #requires:
              #  - static_code_analysis

      - code_coverage:
          context:
            - dockerhub_credentials
            - cpputest_location
          requires:
            - unit_tests

