version: 2.1        
orbs:
  codecov: codecov/codecov@3.2.4

executors:
  master:
    docker:
      - image: dawidblom/etna:latest
        auth:
          username: $DOCKERHUB_USERNAME 
          password: $DOCKERHUB_PASSWORD 

jobs:
  build:
    executor: master
    steps:
      - checkout
      - run:
          name: Building Project
          command: |
            ./scripts/Build.sh Release

  static_code_analysis:
    executor: master
    steps:
      - checkout
      - run:
          name: Static Code Analysis
          command: | 
            ./scripts/Build.sh StaticAnalysis

  unit_tests:
    executor: master
    steps:
      - checkout
      - run:
          name: Unit Tests 
          command: | 
            ./scripts/Build.sh UnitTest

  code_coverage:
    executor: master
    steps:
      - checkout      
      - run:
          name: Code Coverage
          command: |
            ./scripts/Build.sh CodeCoverage
            ./scripts/CodeCoverage.sh          

            
  etna_runner:
    machine: true
    resource_class: djblom/etna
    steps:
      - run:
          name: Start Openocd
          command: |
            cd /home/odin/project
            sudo ./scripts/FlashCode.sh
  

workflows:
  project_workflow:
    jobs:
      - build:
          context:
            - dockerhub_credentials

      - etna_runner:
         requires:
            - build

      - static_code_analysis:
          context:
            - dockerhub_credentials
          requires:
            - build

      - unit_tests:
          context:
            - dockerhub_credentials
            - cpputest_location

      - code_coverage:
          context:
            - dockerhub_credentials
            - cpputest_location
            - CODECOV_TOKEN
          requires:
            - unit_tests

      



