version: 2.1
workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - dockerhub_credentials
      - static_code_analysis:
          context:
            - dockerhub_credentials
      - unit_tests:
          context:
            - dockerhub_credentials
            - cpputest_location
      - code_coverage:
          context:
            - dockerhub_credentials
            - cpputest_location

executors:
  master:
    docker:
      - image: dawidblom/etna:latest
        auth:
          username: $DOCKERHUB_USERNAME 
          password: $DOCKERHUB_PASSWORD 

jobs:
  build:
    executor: master
    steps:
      - checkout
      - run:
          name: Building Project
          command: |
            ./build.sh Release

  static_code_analysis:
    executor: master
    steps:
      - checkout
      - run:
          name: Static Code Analysis
          command: | 
            ./build.sh StaticAnalysis

  unit_tests:
    executor: master
    steps:
      - checkout
      - run:
          name: Unit Tests 
          command: | 
            ./build.sh UnitTest
            
  code_coverage:
    executor: master
    steps:
      - checkout      
      - run:
          name: Code Coverage
          command: |
            ./build.sh CodeCoverage




