version: 2.1
workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - dockerhub_credentials
      - test:
          context:
            - dockerhub_credentials

executors:
  master:
    docker:
      - image: dawidblom/etna:latest
        auth:
          username: $DOCKERHUB_USERNAME 
          password: $DOCKERHUB_PASSWORD 

jobs:
  build:
    environment:
      CPPUTEST_HOME: /home/odin/cpputest
    executor: master
    steps:
      - checkout
      - run:
          name: Building Project
          command: |
            ./build.sh Release
      - run:
          name: Static Code Analysis
          command: | 
            ./build.sh StaticAnalysis

  test:
    executor: master
    steps:
      - checkout 
      - run:
            name: Install Docker Compose
            command: |
              sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose


      - run:
          name: Run container with arguments
          command: |
            docker-compose run --rm --env CPPUTEST_HOME=/home/odin/cpputest 
      - run:
          name: Unit Tests 
          command: | 
            ./build.sh UnitTest
                  
      - run:
          name: Code Coverage
          command: |
            ./build.sh CodeCoverage




