version: 2.1        
orbs:
  codecov: codecov/codecov@3.2.4

executors:
  master:
    docker:
      - image: dawidblom/etna:latest
        auth:
          username: $DOCKERHUB_USERNAME 
          password: $DOCKERHUB_PASSWORD 

jobs:
  build:
    executor: master
    steps:
      - checkout
      - run:
          name: Building Project
          command: |
            ./scripts/Build.sh Release

  static_code_analysis:
    executor: master
    steps:
      - checkout
      - run:
          name: Static Code Analysis
          command: | 
            ./scripts/Build.sh StaticAnalysis

  unit_tests:
    executor: master
    steps:
      - checkout
      - run:
          name: Unit Tests 
          command: | 
            ./scripts/Build.sh UnitTest

  code_coverage:
    executor: master
    steps:
      - checkout      
      - run:
          name: Code Coverage
          command: |
            ./scripts/Build.sh CodeCoverage
            ./scripts/CodeCoverage.sh
            

            
  runner-test:
    machine: true
    resource_class: djblom/etna
    steps:
      - run:
          name: Install Openocd and GDB
          command: |
            sudo dnf install -y openocd
            sudo dnf install -y gdb

      - run:
          name: Start Openocd
          command:
            sudo openocd -f /usr/share/openocd/scripts/board/st_nucleo_f4.cfg -c "init"
      - run:
          name: Start GDB
          command:
            sudo gdb -ex "target remote :3333" -ex "load build/Release/source/Etna.elf" -ex "verify" -ex "continue" -c exit
            echo "Starting gdb"
          #  gdb 
          #  target extended-remote localhost:3333
          #  monitor reset init
          #  monitor flash write_image erase /home/oden/project/build/Release/source/Etna.elf 
          #  monitor reset
          #  arm-none-eabi-gdb -ex "target exetend-remote localhost:3333" -ex "load /home/oden/project/build/Release/source/Etna.elf" -ex "verify" -ex "continue"
            

workflows:
  project_workflow:
    jobs:
      - build:
          context:
            - dockerhub_credentials

      - static_code_analysis:
          context:
            - dockerhub_credentials
          requires:
            - build

      - unit_tests:
          context:
            - dockerhub_credentials
            - cpputest_location

      - code_coverage:
          context:
            - dockerhub_credentials
            - cpputest_location
            - CODECOV_TOKEN
          requires:
            - unit_tests

      - runner-test:
          requires:
            - build
            - unit_tests
              #- static_code_analysis

              #- code_coverage


