version: 2.1
workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - dockerhub_credentials
      - test:
          context:
            - dockerhub_credentials

executors:
  master:
    docker:
      - image: dawidblom/etna@sha256:004041550faedf72b8f0a25d58689a465919dae096b22aa298bce1cc85ea6e24
        auth:
          username: $DOCKERHUB_USERNAME 
          password: $DOCKERHUB_PASSWORD 

jobs:
  build:
    environment:
      CPPUTEST_HOME: /home/odin/cpputest
    executor: master
    steps:
      - checkout
      - run:
          name: Building Project
          command: |
            ./build.sh Release
      - run:
          name: Static Code Analysis
          command: | 
            ./build.sh StaticAnalysis

  test:
    executor: master
    steps:
      - checkout
      - run:
          name: Unit Tests 
          command: | 
            ./build.sh UnitTest
                  
      - run:
          name: Code Coverage
          command: |
            ./build.sh CodeCoverage




