version: 2.1        
orbs:
  codecov: codecov/codecov@3.2.4

executors:
  master:
    docker:
      - image: dawidblom/etna:latest
        auth:
          username: $DOCKERHUB_USERNAME 
          password: $DOCKERHUB_PASSWORD 

jobs:
  build:
    executor: master
    steps:
      - checkout
      - run:
          name: Building Project
          command: |
            ./scripts/Build.sh Release

  static_code_analysis:
    executor: master
    steps:
      - checkout
      - run:
          name: Static Code Analysis
          command: | 
            ./scripts/Build.sh StaticAnalysis

  unit_tests:
    executor: master
    steps:
      - checkout
      - run:
          name: Unit Tests 
          command: | 
            ./scripts/Build.sh UnitTest

  code_coverage:
    executor: master
    steps:
      - checkout      
      - run:
          name: Code Coverage
          command: |
            ./scripts/Build.sh CodeCoverage
            ./scripts/CodeCoverage.sh

      - run:
          name: Install OpenOCD and GDB
          command: |
            dnf install -y openocd
            dnf install -y gdb
            ls /usr/share/openocd/scripts/board/myboard.cfg | grep st_nucleo_f4.cfg

            
  runner-test:
    machine: true
    resource_class: djblom/etna
    steps:
      - run:
          name: Flash Code To MCU
          command: |
            echo "Hello from your runner!"
          #  sudo openocd -f interface/stlink.cfg -f target/stm32f4x.cfg 
          #  sudo gdb -ex "target remote :3333" -ex "load build/Release/source/Etna.elf" -ex "continue"

workflows:
  project_workflow:
    jobs:
      - build:
          context:
            - dockerhub_credentials

      - static_code_analysis:
          context:
            - dockerhub_credentials
          requires:
            - build

      - unit_tests:
          context:
            - dockerhub_credentials
            - cpputest_location

      - code_coverage:
          context:
            - dockerhub_credentials
            - cpputest_location
            - CODECOV_TOKEN
          requires:
            - unit_tests

      - runner-test:
          requires:
            - build
            - unit_tests
              #- static_code_analysis

              #- code_coverage


