name: Etna CI CD
on: 
  pull_request: null
  push:
    branches:
    - feature/*
    
env:
  CPPUTEST_HOME: /home/odin/cpputest
  
jobs:
  BuildProject:
    runs-on: ubuntu-latest
    container: dawidblom/etna:latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Build
      run: scripts/Build.sh Release    
        
  StaticCodeAnalysis:
      runs-on: ubuntu-latest
      container: dawidblom/etna:latest
      steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Static Code Analysis
        run: scripts/Build.sh StaticAnalysis
      
  UnitTests:
      runs-on: ubuntu-latest
      container: dawidblom/etna:latest
      steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Unit Tests
        run: |
          scripts/Build.sh UnitTest
        env:
          CPPUTEST_HOME: ${ env.CPPUTEST_HOME }

  CodeCoverage:
      runs-on: ubuntu-latest
      container: dawidblom/etna:latest
      steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Code Coverage
        run: |
          scripts/Build.sh CodeCoverage
          scripts/CodeCoverage.sh
        env:
          CPPUTEST_HOME: ${ env.CPPUTEST_HOME }

