name: Etna CI CD
on: 
  pull_request: null
  push:
    branches:
    - feature/*
    
    

  test2:
    runs-on: ubuntu-latest
    services:
      my-db:
        image: postgres:12
        ports:
          - "5432:5432"
    steps:
      - name: Run tests
        run: |
          # run tests here
    
  
jobs:
  BuildProject:
    runs-on: ubuntu-latest
    services:
      container: dawidblom/etna:latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Build
      run: scripts/Build.sh Release    
        
  StaticCodeAnalysis:
      needs: BuildProject
      runs-on: ubuntu-latest
      services:
        container: dawidblom/etna:latest
      steps:
      - name: Static Code Analysis
        run: scripts/Build.sh StaticAnalysis
      
  UnitTests:
      needs: StaticCodeAnalysis
      runs-on: ubuntu-latest
      services:
        container: dawidblom/etna:latest
      steps:
      - name: Unit Tests
        run: |
          scripts/Build.sh UnitTest
        env:
          CPPUTEST_HOME: ${{ vars.CPPUTEST_HOME }}

  CodeCoverage:
      needs: UnitTests
      runs-on: ubuntu-latest
      services:
        container: dawidblom/etna:latest
      steps:
      - name: Code Coverage
        run: |
          scripts/Build.sh CodeCoverage
          scripts/CodeCoverage.sh
        env: 
          CPPUTEST_HOME: ${{ vars.CPPUTEST_HOME }}

