name: Etna CI CD
on: 
  pull_request: null
  push:
    branches:
    - feature/*

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SSH_DEPLOY_KEY: ${{ secrets.SSH_COVERAGE_PAGES }}
  
jobs:
  #Build:
    #runs-on: ubuntu-latest
    #container: dawidblom/etna:latest
    #steps:
    #- name: Checkout Code
    #  uses: actions/checkout@v3
    #- name: Build
    #  run: scripts/Build.sh   
      
  Test:
    runs-on: ubuntu-latest
    container: dawidblom/etna:latest       
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    #- name: Static Code Analysis
      #run: scripts/StaticCodeAnalysis.sh

    #- name: Unit Tests
      #run: |
      #  scripts/UnitTests.sh 
      #env:
      #  CPPUTEST_HOME: ${{ vars.CPPUTEST_HOME }}
      
    - name: Set up SSH key
      run: |
        echo "$SSH_DEPLOY_KEY" > deploy_key
        chmod 600 deploy_key
        eval $(ssh-agent -s)
        ssh-add deploy_key
        ssh-keyscan -H github.com

    - name: Code Coverage
      run: |
        scripts/CodeCoverage.sh
      env: 
        CPPUTEST_HOME: ${{ vars.CPPUTEST_HOME }}
    - name: Publish Report
      env:
        GIT_SSH_COMMAND: 'ssh -i deploy_key'
      run: |
        git clone git@github.com:DJBlom/Coverage.git
        
        #cp -R build/codeCoverage/html Coverage/
        #cd Coverage
        #git add .
        #git commit -m "Coverage Report Updated"
        #git push origin main
        
        #git remote set-url origin git@github.com:DJBlom/Coverage.git
        #git config --global user.email "dawidjblom@gmail.com"
        #git config --global user.name "Dawid"
      
        


     
  #HILTesting:
    #runs-on: ubuntu-latest
    #container: dawidblom/etna:latest
    #steps:
    #- name: Checkout Code
    #  uses: actions/checkout@v3
      
    #- name: Performing HIL Testing
    #  run:
    #    echo "Performing Hardware In The Loop Testing"
