name: Etna CI CD
on: 
  pull_request: null
  push:
    branches:
    - feature/*
    
  
jobs:
  #Build:
    #runs-on: ubuntu-latest
    #container: dawidblom/etna:latest
    #steps:
    #- name: Checkout Code
    #  uses: actions/checkout@v3
    #- name: Build
    #  run: scripts/Build.sh   
      
  Test:
    runs-on: ubuntu-latest
    container: dawidblom/etna:latest       
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    #- name: Static Code Analysis
      #run: scripts/StaticCodeAnalysis.sh

    #- name: Unit Tests
      #run: |
      #  scripts/UnitTests.sh 
      #env:
      #  CPPUTEST_HOME: ${{ vars.CPPUTEST_HOME }}

    - name: Code Coverage
      run: |
        scripts/CodeCoverage.sh
      env: 
        CPPUTEST_HOME: ${{ vars.CPPUTEST_HOME }}
    - name: Publish Report
      run: |
        git clone git@github.com:DJBlom/Coverage.git
        cd Coverage
        cp -R ../build/codeCoverage/html .
        git add .
        git commit -m "Coverage Report Updated"
        git push origin main
      env:
         SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}


     
  #HILTesting:
    #runs-on: ubuntu-latest
    #container: dawidblom/etna:latest
    #steps:
    #- name: Checkout Code
    #  uses: actions/checkout@v3
      
    #- name: Performing HIL Testing
    #  run:
    #    echo "Performing Hardware In The Loop Testing"
