name: Etna CI CD
on: 
  pull_request: null
  push:
    branches:
    - feature/*
    
  
jobs:
  BuildProject:
    runs-on: ubuntu-latest
    container: dawidblom/etna:latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Build
      run: scripts/Build.sh    
      
  StaticCodeAnalysis:
    #needs: BuildProject
    runs-on: ubuntu-latest
    container: dawidblom/etna:latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Static Code Analysis
      run: scripts/StaticCodeAnalysis.sh
    
  UnitTests:
    #needs: StaticCodeAnalysis
    runs-on: ubuntu-latest
    container: dawidblom/etna:latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Unit Tests
      run: |
        scripts/UnitTests.sh 
      env:
        CPPUTEST_HOME: ${{ vars.CPPUTEST_HOME }}
        
  CodeCoverage:
    #needs: UnitTests
    runs-on: ubuntu-latest
    container: dawidblom/etna:latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Code Coverage
      run: |
        scripts/CodeCoverage.sh
      env: 
        CPPUTEST_HOME: ${{ vars.CPPUTEST_HOME }}
    - name: Publish Report
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git add build/codeCoverage/html
        git commit -m "Update coverage report"
        git push -f origin gh-pages:gh-pages

