name: Etna CI CD
on: 
  pull_request: null
  push:
    branches:
    - feature/*
    
  
jobs:
  #Build:
    #runs-on: ubuntu-latest
    #container: dawidblom/etna:latest
    #steps:
    #- name: Checkout Code
    #  uses: actions/checkout@v3
    #- name: Build
    #  run: scripts/Build.sh   
      
  Test:
    runs-on: ubuntu-latest
    container: dawidblom/etna:latest       
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    #- name: Static Code Analysis
      #run: scripts/StaticCodeAnalysis.sh

    #- name: Unit Tests
      #run: |
      #  scripts/UnitTests.sh 
      #env:
      #  CPPUTEST_HOME: ${{ vars.CPPUTEST_HOME }}

    - name: Code Coverage
      run: |
        scripts/CodeCoverage.sh
      env: 
        CPPUTEST_HOME: ${{ vars.CPPUTEST_HOME }}
    - name: Publish Report
      uses: cpina/github-action-push-to-another-repository@v1.5.1
      with:
        source-directory: build/codeCoverage/html
        destination-github-usrname: 'DJBlom'
        destination-repository-name: 'https://github.com/DJBlom/Coverage.git'
        user-email: dawidjblom@gmail.com  
        target-branch: main


     
  #HILTesting:
    #runs-on: ubuntu-latest
    #container: dawidblom/etna:latest
    #steps:
    #- name: Checkout Code
    #  uses: actions/checkout@v3
      
    #- name: Performing HIL Testing
    #  run:
    #    echo "Performing Hardware In The Loop Testing"
