name: Etna CI CD
on: 
  pull_request: null
  push:
    branches:
    - feature/*
    
  
jobs:
  #Build:
    #runs-on: ubuntu-latest
    #container: dawidblom/etna:latest
    #steps:
    #- name: Checkout Code
    #  uses: actions/checkout@v3
    #- name: Build
    #  run: scripts/Build.sh   
      
  Test:
    runs-on: ubuntu-latest
    container: dawidblom/etna:latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    #- name: Static Code Analysis
      #run: scripts/StaticCodeAnalysis.sh

    #- name: Unit Tests
      #run: |
      #  scripts/UnitTests.sh 
      #env:
      #  CPPUTEST_HOME: ${{ vars.CPPUTEST_HOME }}

    - name: Code Coverage
      run: |
        scripts/CodeCoverage.sh
        ls
        ls build/codeCoverage/
      env: 
        CPPUTEST_HOME: ${{ vars.CPPUTEST_HOME }}
    - name: Publish Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: build/codeCoverage/html/index.html
     
  #HILTesting:
    #runs-on: ubuntu-latest
    #container: dawidblom/etna:latest
    #steps:
    #- name: Checkout Code
    #  uses: actions/checkout@v3
      
    #- name: Performing HIL Testing
    #  run:
    #    echo "Performing Hardware In The Loop Testing"
