name: Etna CI CD
on: [push]

env:
  CPPUTEST_HOME: ${{ secrets.CPPUTEST_HOME }}
  



jobs:
  build:
    runs-on: ubuntu-latest
    container: dawidblom/etna:latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
   
    - name: Build
      run: scripts/Build.sh Release    
      env:
        CPPUTEST_HOME: ${{ env.CPPUTEST_HOME }}
        
  StaticCodeAnalysis:
      runs-on: ubuntu-latest
      steps:
      - name: Static Code Analysis
        run: scripts/Build.sh StaticAnalysis
        env: 
          CPPUTEST_HOME: ${{ env.CPPUTEST_HOME }}
    #runs-on: ubuntu-latest
    #container: dawidblom/etna:latest
    
    #- name: Checkout Code
    #  uses: actions/checkout@v3
      
    
          #        
          #
          # UnitTests:
          #    runs-on: ubuntu-latest
          #    steps:
          #    - name: Checkout Code
          #      uses: actions/checkout@v3
          #
          #    - name: Unit Tests
          #      run: |
          #        docker run --rm -v $(pwd):/project -w /project dawidblom/etna:latest bash -c "scripts/Build.sh UnitTest"
          #      env:
          #        CPPUTEST_HOME: ${{ env.CPPUTEST_HOME }}
          #
          # CodeCoverage:
          #    runs-on: ubuntu-latest
          #    steps:
          #    - name: Checkout Code
          #      uses: actions/checkout@v3
          #
          #    - name: Code Coverage
          #      run: |
          #        docker run --rm -v $(pwd):/project -w /project dawidblom/etna:latest bash -c "scripts/Build.sh CodeCoverage"
          #      env:
          #        CPPUTEST_HOME: ${{ env.CPPUTEST_HOME }}

