name: Etna CI CD
on: 
  pull_request: null
  push:
    branches:
    - feature/*
    
  
jobs:
  Build:
    runs-on: ubuntu-latest
    container: dawidblom/etna:latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Build
      run: scripts/Build.sh   
      
  Test:
    runs-on: ubuntu-latest
    container: dawidblom/etna:latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    #- name: Static Code Analysis
      #run: scripts/StaticCodeAnalysis.sh

    - name: Unit Tests
      run: |
        scripts/UnitTests.sh 
      env:
        CPPUTEST_HOME: ${{ vars.CPPUTEST_HOME }}

    - name: Code Coverage
      run: |
        scripts/CodeCoverage.sh
      env: 
        CPPUTEST_HOME: ${{ vars.CPPUTEST_HOME }}
    - name: Publish Report
      run: |
        ls
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git add html
        git commit -m "Update coverage report"
        git push -f origin gh-pages:gh-pages
        git config advice.addIgnoredFile false
        
  HILTesting:
    runs-on: ubuntu-latest
    container: dawidblom/etna:latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Performing HIL Testing
      run:
        echo "Performing Hardware In The Loop Testing"
