name: Etna CI CD
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Verify docker creds are there
      run: echo "Docker Token: ${{ vars.DOCKER_TOKEN }}" 

    - name: DockerHub Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

          #    - name: Build
          #      run: |
          #        docker run --rm -v $(pwd):/project -w /project dawidblom/etna:latest bash -c "scripts/Build.sh Release"
          #        
          #    - name: Static Code Analysis
          #      run: |
          #        docker run --rm -v $(pwd):/project -w /project dawidblom/etna:latest bash -c "scripts/Build.sh StaticAnalysis"
          #        
          #    - name: Unit Tests
          #      run: |
          #        docker run --rm -v $(pwd):/project -w /project dawidblom/etna:latest bash -c "scripts/Build.sh UnitTest"
          #    - name: Code Coverage
          #      run: |
          #        docker run --rm -v $(pwd):/project -w /project dawidblom/etna:latest bash -c "scripts/Build.sh CodeCoverage"

