name: Etna CI CD
on: 
  pull_request: null
  push:
    branches:
    - feature/*
  
jobs:
  BuildProject:
    runs-on: ubuntu-latest
    container: dawidblom/etna:latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Build
      run: scripts/Build.sh Release    
        
  StaticCodeAnalysis:
      runs-on: ubuntu-latest
      container: dawidblom/etna:latest
      steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Static Code Analysis
        run: scripts/Build.sh StaticAnalysis
        env: 
          CPPUTEST_HOME: ${{ secrets.CPPUTEST_HOME }}
      
  UnitTests:
      runs-on: ubuntu-latest
      container: dawidblom/etna:latest
      steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Unit Tests
        run: scripts/Build.sh UnitTest
        env:
          CPPUTEST_HOME: ${{ secrets.CPPUTEST_HOME }}

  CodeCoverage:
      runs-on: ubuntu-latest
      container: dawidblom/etna:latest
      steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Code Coverage
        run: scripts/Build.sh CodeCoverage
        env:
          CPPUTEST_HOME: ${{ secrets.CPPUTEST_HOME }}

